### ISSUE TITLE
Optional embed parameters

### ISSUE THREAD

**Issue by n0ct** [micartey/webhookly#1]
In the WebHook::execute method, the use of Optional.of instead of Optional.ofNullable is a problem.
Indeed, this causes every parameter of the embed to become mandatory.

```
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at java.util.Optional.of(Optional.java:113) ~[?:?]
        at me.micartey.webhookly.DiscordWebhook.execute(DiscordWebhook.java:61) ~[le-play-server-utils-1.0-SNAPSHOT.jar:?]
        at ...
```

Try to define the minimum parameters and you will see the issue.

**Comment by micartey** [comment]
Definitely a big mistake. I'll fix this in a week, as I am currently unavailable. You are welcome to create a merge request if you need this faster than that.

**Comment by micartey** [comment]
Should be fixed, please check
